language: php

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

php:
  - '7.3'
  - '7.4'

before_install:

script:
  - composer install
  - composer test

after_success:
  - travis_retry php vendor/bin/php-coveralls
